### PR TITLE
Page for the home page

### PR DESCRIPTION
**Pull request by katiesteele74**
Created a page for the home page.

### CODE REVIEW

**Comment by ethanedwards115** [comment]
All I see is a title which says "home page." Did you commit and push all your changes?

**Comment by ethanedwards115** [comment]
Maybe implement the nav bar from the template and add some filler text and images?

**Comment by ethanedwards115** [comment]
Okay since no action has been taken, I'll do it myself. Feel free to add anything else but all I'm going to add is a filler image and 2 filler paragraphs

**Comment by Arcfej** [comment]
And 2 buttons for the shop and blog pages.

And lets make pull requests only with finished functionalities or bug fixes in the future

**Pull request merged**
